<a href="https://colab.research.google.com/github/owen-george/IronHack_escape_room5/blob/main/Quest_Shark_Attacks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

def import_data(url):
    shark_df = pd.read_excel("https://www.sharkattackfile.net/spreadsheets/GSAF5.xls")
    shark_df.dropna(axis=1, how='all', inplace=True)
    shark_df.dropna(axis=0, how='all', inplace=True)
    return shark_df

shark_df = import_data("https://www.sharkattackfile.net/spreadsheets/GSAF5.xls")

In [ ]:
#Eliska

#Date - date of the indicent
#Year - year of the incident (a duplicate, we can clear this column and merge to the first?)
#Type - Unprovoked, Provoked, Questionable, Watercraft, Air/Sea Disaster
#      - Provoked = "provoked" incident as one in which human actions like capturing, spearing, or hooking a shark may prompt it to bite defensively. (mixed data, orange entries are also classified as "provoked")
#      - Unprovoked =  typically lack such initial aggression from the human side. This distinction helps shark behaviorists assess which incidents reflect a shark’s natural curiosity or defensive behavior, rather than aggression.
#      - Questionable = some incidents lack sufficient data to confirm if injuries were caused by a shark or if a person drowned and was later scavenged by sharks. In certain cases, despite media claims, evidence shows no shark involvement at all.
#      - Watercraft = – Incidents in which a boat was bitten or rammed by a shark are in green.

#NOTE: However, in cases in which the shark was hooked, netted or gaffed, the entry is orange because they are classed as provoked incidents.

#Country, State, Location = in some cases only the country provided and the rest of data missing
#Activity = in which activity the attack occurred
#Name,sex = clear, sometimes name is replaced by gender, so the data is mixed
#age = besides integer we do have strings there, eg. "middle age, teen, 40s", in some cases missing
#Injuries = quite messy,same injuries named differently
#Time = str, eg(afternoon, 11h00,), in some cases range of hours 14h00-15h00
#Species = same shark named differently, eg.Bull shark, Bull shark 6ft, Bull shark 6-7ft
#Sourse = where the info is coming from

In [ ]:
#Vasco
#Choosing what we will be(Surf Company, Shark tracking company...)
#Provoked , unprovoked!!!!
#Origin Place-Country then specify!!
#Year!
#Activity that were doing when the attack was occurred !!!
#Most attacks occurred Men or Women Young or Old!!!
#(!-!!!! importance)

In [ ]:
#Owen

# - Inconsistent naming of countries (some all upper case, some lower, COLUMBIA/COLOMBIA, SRI LANKA/CEYLON, etc.)
# - Age is stored as object (things like "30s" / "young" / "18 or 20")
# - Some years missing or wrong (eg. 0) - Better to take these from date
# - Inconsistent naming of species (eg. "a dog shark" vs "Dog Shark")
# - Sex is stored as 'M', 'F', nan, ' M', 'M ', 'lli', 'M x 2', 'N', '.' (need to use .strip() to fix the "M"/" M"/"M ")
# - Some dates aren't in format (eg. starts with "Reported ")

# Hypotheses:

# What group is at highest risk of attack?
# - More men are attacked than women
# - Some countries have far more attacks than others
# Some species of shark produce far more attacks, and some have higher fatality rates
# Shark attacks have increased in frequency over the last 100 years
# - Swimming is the most dangerous activity for shark attacks
# - There is seasonal variation in shark attacks (split by hemisphere?)

# Business case
# A holiday insurance company trying to establish who/when is at highest risk of shark attack

Educational App for Shark Awareness and Safety

> Business Case
"As a developer of educational and safety apps for ocean-goers, we aim to reduce shark-related incidents by educating users on shark behavior, risk factors, and safe practices. This app will empower users with real-time information and safety guidelines tailored to their location and planned activities."

>Hypothesis
"Educating users about shark encounter risk factors, including location, time of day, and activity type, will increase their awareness and reduce shark-related incidents. This can be achieved by using the Shark Attack dataset to highlight patterns and safety tips for each user."

In [ ]:
#Vasco
#'Date' column to datetime format,errors='coerce' to convert non-date strings to invalid
shark_df['Date'] = pd.to_datetime(shark_df['Date'], errors='coerce')

#drop rows invalid dates
shark_df.dropna(subset=['Date'], inplace=True)

#filter out dates before 1900
shark_df = shark_df[shark_df['Date'] >= pd.Timestamp('1900-01-01')].reset_index(drop=True)

In [ ]:
#Owen - edits to date cleaning
def clean_dates2(df):
    new_df = df.copy()
    #6973 rows
    #Removes "reported" from dates and trailing spaces
    new_df['Date'] = new_df['Date'].str.replace('reported', '', case=False)
    new_df["Date"] = new_df["Date"].apply(lambda x: x.strip() if isinstance(x, str) else x)
    new_df['Date'] = new_df['Date'].str.replace(' ', '-', regex=False)
    new_df['Date'] = new_df['Date'].str.replace(r'-+', '-', regex=True)

    #converts to date format
    new_df['Date'] = pd.to_datetime(new_df['Date'], errors='coerce')

    #drop rows invalid dates
    new_df.dropna(subset=['Date'], inplace=True)
    #5376 rows

    #drop years before 1900
    new_df = new_df[new_df["Year"] >= 1900 ]
    new_df = new_df[new_df['Date'] >= pd.Timestamp('1900-01-01')].reset_index(drop=True)
    #5114 rows

    return new_df

test = clean_dates2(shark_df)

test["Year2"] = test["Date"].dt.year

test[test['Year'] != test['Year2']]

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22,Year2
411,2010-02-01,2020.0,Unprovoked,FRENCH POLYNESIA,Marquesas,Ua Huka,Canoeing,Kevin,M,NaN,...,"TNTV, 2/6/2020",2010.02.01-Kevin.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2020.02.01,2020.02.01,6525.0,NaN,NaN,2010
445,2019-10-25,2018.0,Unprovoked,USA,California,"Cambria, San Luis Obispo County",Kayak fishing,David Zamora,M,NaN,...,D. Zamora,2019.10.25-Zamora.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2019.10.25,2019.10.25,6492.0,NaN,NaN,2019
503,2018-05-09,2019.0,Unprovoked,REUNION ISLAND,NaN,Saint Leu,Surfing,Kim Mahbouli,M,28,...,"K. McMurray, TrackingSharks.com, M. Michaelson...",2019.05.09-Mahbouli.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2019.05.09,2019.05.09,6434.0,NaN,NaN,2018
523,2018-02-18,2019.0,Unprovoked,USA,California,"Dog Beach, Huntington Beach",Surfing,Joel Smith,M,NaN,...,"R. Collier, GSAF",2019.02.18-Smith.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2019.02.18,2019.02.18,6414.0,NaN,NaN,2018
1268,2014-05-14,2013.0,Unprovoked,ECUADOR,Santa Cruz Island,"Playa Brava, Turtle Bay",Surfing,Intriago Diego,M,29,...,"El Universo, 5/16/2013",2013.05.14-Diego.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2013.05.14,2013.05.14,5653.0,NaN,NaN,2014
1495,2008-06-26,2011.0,Unprovoked,USA,North Carolina,"North Topsail Beach, Onslow County",Playing in the surf,Cassidy Cartwright,F,10,...,C. Creswell & G. Hubbell,2011.06.26-Cartwright.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.06.26,2011.06.26,5423.0,NaN,NaN,2008
1530,2010-03-10,2011.0,Invalid,EGYPT,South Sinai Peninsula,Sharm-el-Sheikh,NaN,female,F,NaN,...,"Swindon Advertiser, 3/10/2011",2011.03.10.R-Sharm-scavenging.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.03.10.R,2011.03.10.R,5388.0,NaN,NaN,2010
1772,2006-12-06,2008.0,Watercraft,AUSTRALIA,New South Wales,Mowarry Point,Fishing,"6 m Seaduce - Occupants: Allen Roberts, Jason ...",NaN,NaN,...,S. Chenhall,2008.12.06-boat_Seaducer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2008.12.06,2008.12.06,5142.0,NaN,NaN,2006
3170,1989-07-27,1969.0,Invalid,BERMUDA,NaN,NaN,Scuba diving,Russian male,M,35,...,"LA Times, 7/28/1989",1989.07.27-SovietDiver.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1989.07.27,1989.07.27,3650.0,NaN,NaN,1989
3425,1962-10-23,1982.0,Sea Disaster,USA,Carolina coast,NaN,Yacht Trashman capsized in storm,John Lippoth & Mark Adams,M x 2,NaN,...,"New York Times, 10/31/1982",1982.10.00-Trashman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1982.10.23,1982.10.23,3362.0,NaN,NaN,1962
3984,1964-07-30,1965.0,Provoked,BAHAMAS,Bimini Islands,Lerner Marine Lab,Attempting to anesthetize shark,Karl Kuchnow,M,NaN,...,"H.D. Baldridge, p. 93",1965.07.30-Kuchnow.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1965.07.30,1965.07.30,2700.0,NaN,NaN,1964
4049,1954-02-08,1964.0,Unprovoked,SOUTH AFRICA,Western Cape Province,Muizenberg,Body boarding,Alan Saffery,M,25,...,"D. Davies; M. Levine, GSAF",1964.02.08-Saffery.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1964.02.08,1964.02.08,2618.0,NaN,NaN,1954
4220,1961-07-16,1971.0,Unprovoked,TURKEY,Anatolia,"İnciralti Beach, İzmir",Swimming,İbrahim Karagöz,M,16,...,"C. Moore, GSAF",1961.07.16-Turkey.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1961.07.16,1961.07.16,2427.0,NaN,NaN,1961
4599,1962-12-14,1952.0,Invalid,GUATEMALA,NaN,NaN,Air Disaster,Soledad Castellanos - or - Norma Fig...,F,NaN,...,"The Frederick Post (Maryland), 12/17/1952, p.1",1952.12.14-Guatemala.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1952.12.14,1952.12.14,1916.0,NaN,NaN,1962
5275,1929-08-29,1921.0,Unprovoked,AUSTRALIA,Torres Strait,NaN,NaN,Oku Hayadi,M,NaN,...,"The Register, 8/29/1921",1921.08.29.R-Hayadi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1921.08.29.R,1921.08.29.R,1069.0,NaN,NaN,1929
5342,1914-11-08,1915.0,Unprovoked,AUSTRALIA,New South Wales,Manly,Bathing,Albert Rebecchi,M,NaN,...,"Sydney Morning Herald, 11/9/1915; V.M. Copples...",1915.11.08-Rebecchi.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1915.11.08,1915.11.08,991.0,NaN,NaN,1914

In [ ]:
#Eliska
def clean_states(df: pd.DataFrame):

    version_2 = shark_df.copy() #independent copy so we wont mess the potential DF
    version_2 = version_2.dropna(subset=["State"]) #get rid of empty values
    version_2.loc[:, "State"] = version_2["State"].str.lower() #convert to lowercase

    #get rid of countries that occur 5 or less times
    state_counts = version_2["State"].value_counts()
    threshold = 5
    states_to_keep = state_counts[state_counts >= threshold].index
    version_2 = version_2[version_2["State"].isin(states_to_keep)]

    #corrections
    state_corrections = {"westerm australia": "western australia", "western australia" : "western australia",
                        "mirs bay ": "mirs bay", "mirs bay" : "mirs bay",
                        "baja california" : "california",
                        " primorje-gorski kotar county": "primorje-gorski kotar county",
                        }
    version_2["State"] = version_2["State"].replace(state_corrections) # apply corrections
    version_2["State"] = version_2["State"].str.title() #get back the capital letter of each word in states

    return version_2

#version_2 = clean_states(version_1)
#version_2["State"].nunique()

In [ ]:
#Owen
def clean_cols(df: pd.DataFrame):
    """Removes empty columns and named "Fatal" correctly """
    new_df = df.rename(columns={'Unnamed: 11': 'Fatal'})
    new_df = new_df.drop(['href formula', 'href','Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22', "pdf"], axis=1)
    new_df = new_df.drop_duplicates()
    return new_df

In [ ]:
#Constanza

def clean_type(df: pd.DataFrame):
    """ Cleans "type" column """
    new_df = df.copy()
    new_df['Type'] = new_df['Type'].replace({' Provoked': 'Provoked'})

    values_to_replace = ['Questionable', 'Watercraft', 'Sea Disaster', '?', 'Unconfirmed', 'Unverified', 'Invalid', 'Under investigation', 'Boat']
    new_df['Type'] = new_df['Type'].replace(values_to_replace, 'Unknown')

    return new_df

In [ ]:
#Owen
def clean_country(df):
    """Tidies the "Country" column of the DataFrama """
    new_df = df.copy()
    new_df = new_df.dropna(subset=["Country"])

    # Converts country column to consistent capitalisation and strips spaces
    new_df["Country"] = new_df["Country"].apply(lambda x: x.strip().title())
    new_df["Country"] = new_df["Country"].apply(lambda x: "USA" if x == "Usa" else x)

    #Removes rows that contain Oceans and Seas for the country
    new_df = new_df[~new_df["Country"].str.contains("Ocean", na=False)]
    new_df = new_df[~new_df["Country"].str.contains("Central Pacific", na=False)]
    new_df = new_df[~new_df["Country"].str.contains(" Sea", na=False)]
    new_df = new_df[~new_df["Country"].str.contains("Persian Gulf", na=False)]

    #Corrects country names
    new_df["Country"] = new_df["Country"].replace("Ceylon (Sri Lanka)", "Sri Lanka")
    new_df["Country"] = new_df["Country"].replace("Ceylon", "Sri Lanka")
    new_df["Country"] = new_df["Country"].replace("Maldive Islands", "Maldives")
    new_df["Country"] = new_df["Country"].replace("St. Maartin", "St Martin")
    new_df["Country"] = new_df["Country"].replace("St. Martin", "St Martin")
    new_df["Country"] = new_df["Country"].replace("Reunion Island", "Reunion")
    new_df["Country"] = new_df["Country"].replace("Trinidad", "Trinidad & Tobago")
    new_df["Country"] = new_df["Country"].replace("Tobago", "Trinidad & Tobago")
    new_df["Country"] = new_df["Country"].replace("Turks And Caicos", "Turks & Caicos")
    new_df["Country"] = new_df["Country"].replace("Sudan?", "Sudan")
    new_df["Country"] = new_df["Country"].replace("United Arab Emirates (Uae)?", "United Arab Emirates")
    new_df["Country"] = new_df["Country"].replace("United Arab Emirates (Uae)", "United Arab Emirates")
    new_df["Country"] = new_df["Country"].replace("Western Samoa", "Samoa")
    new_df["Country"] = new_df["Country"].replace("Scotland", "United Kingdom")
    new_df["Country"] = new_df["Country"].replace("Crete", "Greece")
    new_df["Country"] = new_df["Country"].replace("Okinawa", "Japan")
    new_df["Country"] = new_df["Country"].replace("Columbia", "Colombia")
    new_df["Country"] = new_df["Country"].replace("England", "United Kingdom")
    new_df["Country"] = new_df["Country"].replace("New Britain", "Papua New Guinea")
    new_df["Country"] = new_df["Country"].replace("New Guinea", "Papua New Guinea")
    new_df["Country"] = new_df["Country"].replace('St Helena, British Overseas Territory', "St Helena")
    new_df["Country"] = new_df["Country"].replace('Burma', "Myanmar")

    #Counts occurences of each country
    country_counts = new_df["Country"].value_counts() #Contains 6923


    # Filter countries that appear more than two times
    countries_to_keep = country_counts[country_counts > 1].index
    new_df = new_df[new_df["Country"].isin(countries_to_keep)]

    return new_df

In [ ]:
#Owen

def hemisphere(df: pd.DataFrame):
    """Adds in a "Hemisphere" column using a dictionary to determine which hemisphere the country is in """

    new_df = df.copy()

    hemi_dict = {
        'American Samoa': "South",
        'Antigua': 'North',
        'Argentina': "South",
        'Australia': "South",
        'Azores': "North",
        'Bahamas': "North",
        'Barbados': "North",
        'Belize': "North",
        'Bermuda': "North",
        'Brazil': "Equator",
        'Myanmar': "North",
        'Canada': "North",
        'Cape Verde': "North",
        'Cayman Islands': "North",
        'Chile': "South",
        'China': "North",
        'Colombia': "Equator",
        'Costa Rica': "North",
        'Croatia': "North",
        'Cuba': "North",
        'Dominican Republic': "North",
        'Ecuador': "Equator",
        'Egypt': "North",
        'El Salvador': "North",
        'Fiji': "South",
        'France': "North",
        'French Polynesia': "South",
        'Greece': "North",
        'Grenada': "North",
        'Guam': "North",
        'Guinea': "North",
        'Guyana': "North",
        'Haiti': "North",
        'Honduras': "North",
        'Hong Kong': "North",
        'Iceland': "North",
        'India': "North",
        'Indonesia': "Equator",
        'Iran': "North",
        'Iraq': "North",
        'Ireland': "North",
        'Israel': "North",
        'Italy': "North",
        'Jamaica': "North",
        'Japan': "North",
        'Johnston Island': "North",
        'Kenya': "Equator",
        'Kiribati': "Equator",
        'Lebanon': "North",
        'Liberia': "North",
        'Libya': "North",
        'Madagascar': "South",
        'Malaysia': "North",
        'Maldives': "Equator",
        'Malta': "North",
        'Marshall Islands': "North",
        'Martinique': "North",
        'Mauritius': "South",
        'Mexico': "North",
        'Micronesia': "North",
        'Montenegro': "North",
        'Mozambique': "South",
        'Namibia': "South",
        'New Caledonia': "South",
        'New Zealand': "South",
        'Nicaragua': "North",
        'Nigeria': "North",
        'Norway': "North",
        'Palau': "North",
        'Panama': "North",
        'Papua New Guinea': "South",
        'Peru': "South",
        'Philippines': "North",
        'Portugal': "North",
        'Reunion': "South",
        'Russia': "North",
        'Samoa': "South",
        'Saudi Arabia': "North",
        'Senegal': "North",
        'Seychelles': "South",
        'Sierra Leone': "North",
        'Singapore': "North",
        'Solomon Islands': "South",
        'Somalia': "Equator",
        'South Africa': "South",
        'South Korea': "North",
        'Spain': "North",
        'Sri Lanka': "South",
        'St Helena, British Overseas Territory': "South",
        'St Martin': "North",
        'St Helena': "South",
        'Sudan': "North",
        'Taiwan': "North",
        'Tanzania': "Equator",
        'Thailand': "North",
        'Tonga': "South",
        'Trinidad & Tobago': "North",
        'Tunisia': "North",
        'Turkey': "North",
        'Turks & Caicos': "North",
        'USA': "North",
        'United Arab Emirates': "North",
        'United Kingdom': "North",
        'Uruguay': "South",
        'Vanuatu': "South",
        'Venezuela': "North",
        'Vietnam': "North",
        'West Indies': "North",
        'Yemen': "North"
    }

    #is assigning a "Hemisphere" column to new_df by mapping each entry in the "Country" column to a hemisphere based on a dictionary, hemi_dict.
    new_df["Hemisphere"] = new_df["Country"].apply(lambda country: hemi_dict.get(country, "Na"))

    #Code here
    return new_df

In [ ]:
#filip

#shark_df["Sex"] = shark_df["Sex"].replace({ ' M': 'M', 'M ': 'M', 'M x 2': 'M',})
#shark_df["Sex"] = shark_df["Sex"].replace(['.', 'lli', 'N'], np.nan)

In [ ]:
#filip
def clean_sex(df):
    df2 = df.copy()
    df2["Sex"] = df2["Sex"].replace({ ' M': 'M', 'M ': 'M', 'M x 2': 'M',})
    df2["Sex"] = df2["Sex"].replace(['.', 'lli', 'N'], np.nan)
    return df2

In [ ]:
#filip

def clean_age(shark_df):
    shark_df["Age"] = shark_df["Age"].replace({
        '30s': '30',
        '20/30': '25',
        '20s': '20',
        '50s': '50',
        '40s': '40',
        '60s': '60',
        "20's": '20',
        '18 months': '2',
        '18 or 20': '19',
        '12 or 13': '13',
        '8 or 10': '9',
        '30 or 36': '33',
        '6½': '6',
        '21 & ?': '21',
        '33 or 37': '35',
        'mid-30s': '35',
        '23 & 20': '21',
        '28': '28',
        '20?': '20',
        "60's": '62',
        '32 & 30': '31',
        '16 to 18': '17',
        'mid-20s': '25',
        'Ca. 33': '33',
        '45 ': '45',
        '21 or 26': '24',
        '20 ': '20',
        '>50': '55',
        '18 to 22': '20',
        '9 & 12': '10',
        '? & 19': '19',
        '9 months': '1',
        '25 to 35': '30',
        '23 & 26': '24',
        '33 & 37': '35',
        '25 or 28': '26',
        '30 & 32': '31',
        '50 & 30': '40',
        '13 or 18': '16',
        '34 & 19': '31',
        '33 & 26': '30',
        '2 to 3 months': '1',
        '43': '43',
        '7 or 8': '8',
        '17 & 16': '17',
        'Both 11': '11',
        '9 or 10': '10',
        '36 & 23': '30',
        '10 or 12': '11',
        '31 or 33': '32',
        '2½': '2',
        '13 or 14': '14'
    })

    shark_df["Age"] = shark_df["Age"].str.strip()
    shark_df["Age"] = shark_df["Age"].replace([
        'Middle age', np.nan, '?',
        '!2', 'teen', 'Teen', '!6', '!!', '45 and 15', '28 & 22',
        '9 & 60', 'a minor', '28 & 26', '46 & 34', '28, 23 & 30', 'Teens',
        '36 & 26', '\xa0', ' ', '7      &    31',
        'Elderly', 'adult', '(adult)',
        '37, 67, 35, 27, ? & 27', '21, 34,24 & 35', '17 & 35',
        'X', '"middle-age"', 'MAKE LINE GREEN', '"young"', 'F',
        'young', '  ', 'A.M.',
           '?    &   14', 'M', '',
    ], np.nan)
    return(shark_df)

In [ ]:
import pandas as pd
import numpy as np

shark_df = import_data("https://www.sharkattackfile.net/spreadsheets/GSAF5.xls")

def cleaning(df):
    df2 = df.copy()
    df2 = clean_dates2(df2)
    df2 = clean_country(df2)
    df2 = hemisphere(df2)
    df2 = clean_type(df2)
    df2 = clean_states(df2)
    df2 = clean_age(df2)
    df2 = clean_sex(df2)
    df2 = clean_cols(df2)
    return df2

df = cleaning(shark_df)

cleaning(shark_df).head()

NameError: name 'clean_country' is not defined